In [2]:
x = 15   # enter == go down one line
y = 20   # enter == go down one line
print(f'{x} * {y} = {x*y}')   # shift + enter == execute the cell

15 * 20 = 300


In [3]:
# in Jupyter, if the final line of a cell is an expression (i.e., returns a value)
# then that expression is returned by Jupyter

x

15

In [4]:
x*2

30

In [4]:
x*2

30

In [5]:
x+3

18

In [6]:
# green outline -- edit mode / programming mode  (press ENTER in command mode)
# blue outline -- command mode  (press ESC in edit mode)

In [7]:
# in command mode, keys have new meanings!

# x -- cut
# c -- copy
# v -- paste

In [8]:
# in command mode, you can say:

# m -- make this cell Markdown
# y -- make this cell code
# r -- make this cell raw text (whatever you want to type)

# Headline

This is in Markdown!  And it's along with my code!

- Easier to read
- Easier to type
- Fun to show off to friends and family!
    1. Friends
    2. Family

In [9]:
import time

for i in range(10):
    time.sleep(5)
    

KeyboardInterrupt: 

In [10]:
# Jupyter's "magic" commands
# - these are special commands that start with %
# - They are interpreted by Jupyter, and not sent to Python

In [11]:
%pwd

'/Users/reuven/Consulting/Courses/Data Science/cisco-2020-september'

In [12]:
%ls

'Cisco — 2020 September 21.ipynb'   files/


In [13]:
# Load the things we need for NumPy
# make sure that visualization will be inside of the browser

%pylab inline

Populating the interactive namespace from numpy and matplotlib


In [17]:
%lsmagic

Available line magics:
%alias  %alias_magic  %autoawait  %autocall  %automagic  %autosave  %bookmark  %cat  %cd  %clear  %colors  %conda  %config  %connect_info  %cp  %debug  %dhist  %dirs  %doctest_mode  %ed  %edit  %env  %gui  %hist  %history  %killbgscripts  %ldir  %less  %lf  %lk  %ll  %load  %load_ext  %loadpy  %logoff  %logon  %logstart  %logstate  %logstop  %ls  %lsmagic  %lx  %macro  %magic  %man  %matplotlib  %mkdir  %more  %mv  %notebook  %page  %pastebin  %pdb  %pdef  %pdoc  %pfile  %pinfo  %pinfo2  %pip  %popd  %pprint  %precision  %prun  %psearch  %psource  %pushd  %pwd  %pycat  %pylab  %qtconsole  %quickref  %recall  %rehashx  %reload_ext  %rep  %rerun  %reset  %reset_selective  %rm  %rmdir  %run  %save  %sc  %set_env  %store  %sx  %system  %tb  %time  %timeit  %unalias  %unload_ext  %who  %who_ls  %whos  %xdel  %xmode

Available cell magics:
%%!  %%HTML  %%SVG  %%bash  %%capture  %%debug  %%file  %%html  %%javascript  %%js  %%latex  %%markdown  %%perl  %%prun  %%pypy  %%

In [15]:
np

<module 'numpy' from '/usr/local/lib/python3.8/site-packages/numpy/__init__.py'>

In [16]:
np.__version__

'1.19.2'

In [18]:
%whos

Variable   Type    Data/Info
----------------------------
i          int     5
x          int     15
y          int     20


In [19]:
# NumPy n-dimensional array
np.ndarray

numpy.ndarray

In [20]:
# don't use this directly!
np.ndarray()

TypeError: ndarray() missing required argument 'shape' (pos 1)

In [21]:
# instead, use np.array -- a shortcut that's easier for people to use each day
a = np.array([10, 20, 30, 40, 50])

a

array([10, 20, 30, 40, 50])

In [22]:
type(a)

numpy.ndarray

In [23]:
a[2]

30

In [25]:
a[0]

10

In [26]:
a[-1]

50

# Exercise: Simple NumPy arrays

1. Load `numpy` with `%pylab inline`
2. Create a new array with some integers (you can choose)
3. Retrieve the item at index 0.
4. Retrieve the final item.
5. Retrieve the item at index 2.

In [27]:
a = np.array([2,4,6,10, 73, 15, 12])


In [28]:
a[0]

2

In [29]:
a[-1]

12

In [30]:
a[2]

6

In [31]:
a[len(a)-1]

12

In [32]:
# create an array with a range

for i in range(10):
    print(i, end=' ')

0 1 2 3 4 5 6 7 8 9 

In [33]:
for i in range(10,20):
    print(i, end=' ')

10 11 12 13 14 15 16 17 18 19 

In [34]:
for i in range(10,30,4):
    print(i, end=' ')

10 14 18 22 26 

In [35]:
np.array(range(10, 30, 4))

array([10, 14, 18, 22, 26])

In [36]:
np.arange(10, 30, 4)

array([10, 14, 18, 22, 26])

In [39]:
# returns a NumPy array of length 10 with all elements randomly chosen from 0-100
np.random.randint(0, 100, 10)

array([19, 87, 37, 14, 42, 20, 47,  3, 14, 23])

In [40]:
# if I want floats, it works a bit differently:
np.random.rand(10)  # returns 10 floats, each from 0-1

array([0.41933667, 0.74539399, 0.17332654, 0.86647086, 0.54275572,
       0.57917041, 0.9093446 , 0.50572389, 0.43328061, 0.96013093])

In [41]:
# get an array that's only ones
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [42]:
# get an array that's only zeroes
np.zeros(10)   #notice the spelling -- zeros, not zeroes!

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [43]:
mylist = [10, 20, 30, 40, 50]

mylist + mylist

[10, 20, 30, 40, 50, 10, 20, 30, 40, 50]

In [44]:
mylist + 3

TypeError: can only concatenate list (not "int") to list

In [45]:
a = np.array([10, 20, 30, 40, 50])

a+a

array([ 20,  40,  60,  80, 100])

In [46]:
a-a

array([0, 0, 0, 0, 0])

In [47]:
a/a

array([1., 1., 1., 1., 1.])

In [48]:
a*a

array([ 100,  400,  900, 1600, 2500])

In [49]:
b = np.array([100, 200, 300])

a + b

ValueError: operands could not be broadcast together with shapes (5,) (3,) 

In [50]:
a

array([10, 20, 30, 40, 50])

In [51]:
a * 3  # broadcasting

array([ 30,  60,  90, 120, 150])

In [52]:
a+3

array([13, 23, 33, 43, 53])

In [53]:
a-3

array([ 7, 17, 27, 37, 47])

In [54]:
a*3

array([ 30,  60,  90, 120, 150])

In [55]:
a/3

array([ 3.33333333,  6.66666667, 10.        , 13.33333333, 16.66666667])

In [56]:
a**3

array([  1000,   8000,  27000,  64000, 125000])

In [57]:
a%3

array([1, 2, 0, 1, 2])

In [58]:
np.ones(10) * 5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [59]:
np.random.rand(10) * 100 

array([30.36870853,  2.18917801, 19.81057202, 43.23619841, 69.90347056,
       57.85774904, 64.1121577 , 79.49714839, 90.1011269 , 43.53121222])

In [60]:
a


array([10, 20, 30, 40, 50])

In [61]:
a.sum()

150

In [63]:
a.size

5

In [64]:
a.mean()

30.0

In [65]:
a.min()

10

In [66]:
a.max()

50

In [67]:
a.std()

14.142135623730951

In [68]:
a = np.random.randint(0, 100, 15)
a

array([26, 86, 54, 35, 80, 15, 32,  7, 90, 31,  0, 13, 60, 40, 76])

In [70]:
np.ones(a.size)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [71]:
a

array([26, 86, 54, 35, 80, 15, 32,  7, 90, 31,  0, 13, 60, 40, 76])

In [72]:
a.size

15

In [76]:
new_a = np.zeros(20)
new_a[:a.size] = a

In [77]:
new_a

array([26., 86., 54., 35., 80., 15., 32.,  7., 90., 31.,  0., 13., 60.,
       40., 76.,  0.,  0.,  0.,  0.,  0.])

# Exercises: More NumPy manipulations!

1. Create an array of 5 random integers between 0 and 100
2. What is the mean of these integers? What is their standard deviation?
3. Create an array of 100 random ints between 0 and 100.
4. Once again, get the mean + std. Is it higher or lower than what you got in #2?


In [78]:
a = np.random.randint(0, 100, 5)
a


array([44, 89,  4, 25, 63])

In [79]:
a.mean()

45.0

In [80]:
a.std()

29.468627385747034