In [2]:
x = 15   # enter == go down one line
y = 20   # enter == go down one line
print(f'{x} * {y} = {x*y}')   # shift + enter == execute the cell

15 * 20 = 300


In [3]:
# in Jupyter, if the final line of a cell is an expression (i.e., returns a value)
# then that expression is returned by Jupyter

x

15

In [4]:
x*2

30

In [4]:
x*2

30

In [5]:
x+3

18

In [6]:
# green outline -- edit mode / programming mode  (press ENTER in command mode)
# blue outline -- command mode  (press ESC in edit mode)

In [7]:
# in command mode, keys have new meanings!

# x -- cut
# c -- copy
# v -- paste

In [8]:
# in command mode, you can say:

# m -- make this cell Markdown
# y -- make this cell code
# r -- make this cell raw text (whatever you want to type)

# Headline

This is in Markdown!  And it's along with my code!

- Easier to read
- Easier to type
- Fun to show off to friends and family!
    1. Friends
    2. Family

In [9]:
import time

for i in range(10):
    time.sleep(5)
    

KeyboardInterrupt: 

In [10]:
# Jupyter's "magic" commands
# - these are special commands that start with %
# - They are interpreted by Jupyter, and not sent to Python

In [11]:
%pwd

'/Users/reuven/Consulting/Courses/Data Science/cisco-2020-september'

In [12]:
%ls

'Cisco — 2020 September 21.ipynb'   files/


In [13]:
# Load the things we need for NumPy
# make sure that visualization will be inside of the browser

%pylab inline

Populating the interactive namespace from numpy and matplotlib


In [17]:
%lsmagic

Available line magics:
%alias  %alias_magic  %autoawait  %autocall  %automagic  %autosave  %bookmark  %cat  %cd  %clear  %colors  %conda  %config  %connect_info  %cp  %debug  %dhist  %dirs  %doctest_mode  %ed  %edit  %env  %gui  %hist  %history  %killbgscripts  %ldir  %less  %lf  %lk  %ll  %load  %load_ext  %loadpy  %logoff  %logon  %logstart  %logstate  %logstop  %ls  %lsmagic  %lx  %macro  %magic  %man  %matplotlib  %mkdir  %more  %mv  %notebook  %page  %pastebin  %pdb  %pdef  %pdoc  %pfile  %pinfo  %pinfo2  %pip  %popd  %pprint  %precision  %prun  %psearch  %psource  %pushd  %pwd  %pycat  %pylab  %qtconsole  %quickref  %recall  %rehashx  %reload_ext  %rep  %rerun  %reset  %reset_selective  %rm  %rmdir  %run  %save  %sc  %set_env  %store  %sx  %system  %tb  %time  %timeit  %unalias  %unload_ext  %who  %who_ls  %whos  %xdel  %xmode

Available cell magics:
%%!  %%HTML  %%SVG  %%bash  %%capture  %%debug  %%file  %%html  %%javascript  %%js  %%latex  %%markdown  %%perl  %%prun  %%pypy  %%

In [15]:
np

<module 'numpy' from '/usr/local/lib/python3.8/site-packages/numpy/__init__.py'>

In [16]:
np.__version__

'1.19.2'

In [18]:
%whos

Variable   Type    Data/Info
----------------------------
i          int     5
x          int     15
y          int     20


In [19]:
# NumPy n-dimensional array
np.ndarray

numpy.ndarray

In [20]:
# don't use this directly!
np.ndarray()

TypeError: ndarray() missing required argument 'shape' (pos 1)

In [21]:
# instead, use np.array -- a shortcut that's easier for people to use each day
a = np.array([10, 20, 30, 40, 50])

a

array([10, 20, 30, 40, 50])

In [22]:
type(a)

numpy.ndarray

In [23]:
a[2]

30

In [25]:
a[0]

10

In [26]:
a[-1]

50

# Exercise: Simple NumPy arrays

1. Load `numpy` with `%pylab inline`
2. Create a new array with some integers (you can choose)
3. Retrieve the item at index 0.
4. Retrieve the final item.
5. Retrieve the item at index 2.

In [27]:
a = np.array([2,4,6,10, 73, 15, 12])


In [28]:
a[0]

2

In [29]:
a[-1]

12

In [30]:
a[2]

6

In [31]:
a[len(a)-1]

12

In [32]:
# create an array with a range

for i in range(10):
    print(i, end=' ')

0 1 2 3 4 5 6 7 8 9 

In [33]:
for i in range(10,20):
    print(i, end=' ')

10 11 12 13 14 15 16 17 18 19 

In [34]:
for i in range(10,30,4):
    print(i, end=' ')

10 14 18 22 26 

In [35]:
np.array(range(10, 30, 4))

array([10, 14, 18, 22, 26])

In [36]:
np.arange(10, 30, 4)

array([10, 14, 18, 22, 26])

In [39]:
# returns a NumPy array of length 10 with all elements randomly chosen from 0-100
np.random.randint(0, 100, 10)

array([19, 87, 37, 14, 42, 20, 47,  3, 14, 23])

In [40]:
# if I want floats, it works a bit differently:
np.random.rand(10)  # returns 10 floats, each from 0-1

array([0.41933667, 0.74539399, 0.17332654, 0.86647086, 0.54275572,
       0.57917041, 0.9093446 , 0.50572389, 0.43328061, 0.96013093])

In [41]:
# get an array that's only ones
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [42]:
# get an array that's only zeroes
np.zeros(10)   #notice the spelling -- zeros, not zeroes!

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [43]:
mylist = [10, 20, 30, 40, 50]

mylist + mylist

[10, 20, 30, 40, 50, 10, 20, 30, 40, 50]

In [44]:
mylist + 3

TypeError: can only concatenate list (not "int") to list

In [45]:
a = np.array([10, 20, 30, 40, 50])

a+a

array([ 20,  40,  60,  80, 100])

In [46]:
a-a

array([0, 0, 0, 0, 0])

In [47]:
a/a

array([1., 1., 1., 1., 1.])

In [48]:
a*a

array([ 100,  400,  900, 1600, 2500])

In [49]:
b = np.array([100, 200, 300])

a + b

ValueError: operands could not be broadcast together with shapes (5,) (3,) 

In [50]:
a

array([10, 20, 30, 40, 50])

In [51]:
a * 3  # broadcasting

array([ 30,  60,  90, 120, 150])

In [52]:
a+3

array([13, 23, 33, 43, 53])

In [53]:
a-3

array([ 7, 17, 27, 37, 47])

In [54]:
a*3

array([ 30,  60,  90, 120, 150])

In [55]:
a/3

array([ 3.33333333,  6.66666667, 10.        , 13.33333333, 16.66666667])

In [56]:
a**3

array([  1000,   8000,  27000,  64000, 125000])

In [57]:
a%3

array([1, 2, 0, 1, 2])

In [58]:
np.ones(10) * 5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [59]:
np.random.rand(10) * 100 

array([30.36870853,  2.18917801, 19.81057202, 43.23619841, 69.90347056,
       57.85774904, 64.1121577 , 79.49714839, 90.1011269 , 43.53121222])

In [60]:
a


array([10, 20, 30, 40, 50])

In [61]:
a.sum()

150

In [63]:
a.size

5

In [64]:
a.mean()

30.0

In [65]:
a.min()

10

In [66]:
a.max()

50

In [67]:
a.std()

14.142135623730951

In [68]:
a = np.random.randint(0, 100, 15)
a

array([26, 86, 54, 35, 80, 15, 32,  7, 90, 31,  0, 13, 60, 40, 76])

In [70]:
np.ones(a.size)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [71]:
a

array([26, 86, 54, 35, 80, 15, 32,  7, 90, 31,  0, 13, 60, 40, 76])

In [72]:
a.size

15

In [76]:
new_a = np.zeros(20)
new_a[:a.size] = a

In [77]:
new_a

array([26., 86., 54., 35., 80., 15., 32.,  7., 90., 31.,  0., 13., 60.,
       40., 76.,  0.,  0.,  0.,  0.,  0.])

# Exercises: More NumPy manipulations!

1. Create an array of 5 random integers between 0 and 100
2. What is the mean of these integers? What is their standard deviation?
3. Create an array of 100 random ints between 0 and 100.
4. Once again, get the mean + std. Is it higher or lower than what you got in #2?


In [78]:
a = np.random.randint(0, 100, 5)
a


array([44, 89,  4, 25, 63])

In [79]:
a.mean()

45.0

In [80]:
a.std()

29.468627385747034

In [81]:
45 - 29

16

In [82]:
45 + 29

74

In [83]:
a = np.random.randint(0, 100, 100)
a

array([61, 77, 64, 69, 25, 60, 81, 95, 59, 26,  4, 62, 90, 10, 95, 54, 20,
       20,  7, 28, 97,  2, 67, 55, 42, 93, 44,  2, 25, 78,  0, 46, 11, 86,
       78, 19, 48, 41, 40, 12, 43, 81, 18, 16, 52, 28,  5, 63, 87, 76, 49,
       59, 58, 59, 40, 19, 87, 38, 57,  9, 58,  2, 32, 39, 49, 30, 74, 55,
       63, 32, 44, 62, 48, 21, 91, 98, 44, 87, 19, 85, 71, 46, 81, 54, 59,
        3, 34, 68, 37, 53, 99,  8, 44, 19, 65,  5, 16, 62, 92, 61])

In [84]:
a.mean()

48.47

In [85]:
a.std()

27.714059608797843

In [86]:
a = np.random.randint(0, 100, 10000)
a.mean()

49.4521

In [87]:
a = np.random.randint(0, 100, 25)

In [88]:
a

array([48, 15, 13, 52, 37,  7, 16,  7, 81, 71, 46, 79, 41, 43, 14, 71, 73,
        4, 50, 69, 87,  7, 81, 77, 22])

In [89]:
# I want the element at index 10
# also the element at index 15

a[10]

46

In [90]:
a[15]

71

In [91]:
# fancy indexing!  ask for *BOTH* at the same time!
a[ [10, 15] ]

array([46, 71])

In [92]:
a[ [10, 15, 10, 15] ]

array([46, 71, 46, 71])

In [93]:
a = np.array([10, 20, 30, 40, 50])
a

array([10, 20, 30, 40, 50])

In [94]:
# retrieve one item
a[3]

40

In [95]:
# retrieve multiple items with "fancy indexing"
a[[2,4]]

array([30, 50])

In [96]:
# use a list / array of boolean values (True/False) as a "mask index" / "boolean index"
a[  [True, False, True, True, False]   ]

array([10, 30, 40])

In [97]:
# T   F  T  T  F
# 10 20 30 40 50



In [98]:
a

array([10, 20, 30, 40, 50])

In [99]:
a + 5

array([15, 25, 35, 45, 55])

In [100]:
a < 30

array([ True,  True, False, False, False])

In [101]:
# this returns all values of a that are < 30 

# how?  2 steps:
# (1) create a boolean array (a<30)
# (2) apply that boolean array to a, getting only those values where the boolean is True

a[a<30]

array([10, 20])

In [102]:
a[a<a.mean()]

array([10, 20])

In [103]:
a[a<=a.mean()]

array([10, 20, 30])

In [104]:
a <= a.mean()

array([ True,  True,  True, False, False])

In [105]:
a[a<= a.mean()]

array([10, 20, 30])

# Exercises: NumPy and boolean indexes

1. Create a NumPy array with 25 random indegers between 0 and 100.
2. Find the odd numbers in this array.
3. Find the even numbers less than 20.  (Note: You'll need to do this in 2 steps for now.)
4. Find the even numbers between 30 and 70 (Again, you'll need to do this in 3 steps.)
5. Get the 1st, 3rd, and 5th numbers between 30 and 70 

In [106]:
a = np.random.randint(0, 100, 25)
a

array([67,  5, 84, 66, 86, 46, 11, 11, 60, 59,  4, 93, 41, 79, 96, 11, 86,
       75, 58, 20, 43, 60, 93, 46, 83])

In [107]:
a%2

array([1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0,
       1, 0, 1])

In [108]:
a

array([67,  5, 84, 66, 86, 46, 11, 11, 60, 59,  4, 93, 41, 79, 96, 11, 86,
       75, 58, 20, 43, 60, 93, 46, 83])

In [109]:
a%2==1   # returns a boolean array showing where we have odd numbers

array([ True,  True, False, False, False, False,  True,  True, False,
        True, False,  True,  True,  True, False,  True, False,  True,
       False, False,  True, False,  True, False,  True])

In [110]:
a

array([67,  5, 84, 66, 86, 46, 11, 11, 60, 59,  4, 93, 41, 79, 96, 11, 86,
       75, 58, 20, 43, 60, 93, 46, 83])

In [111]:
a[a%2==1]

array([67,  5, 11, 11, 59, 93, 41, 79, 11, 75, 43, 93, 83])

In [112]:
a%2==0

array([False, False,  True,  True,  True,  True, False, False,  True,
       False,  True, False, False, False,  True, False,  True, False,
        True,  True, False,  True, False,  True, False])

In [113]:
a[a%2==0]

array([84, 66, 86, 46, 60,  4, 96, 86, 58, 20, 60, 46])

In [114]:
# if you do this, then you're changing a!
# a = a[a%2==0]

b = a[a%2==0]
b

array([84, 66, 86, 46, 60,  4, 96, 86, 58, 20, 60, 46])

In [115]:
mylist = [10, 20, 30, 40, 50]
x = mylist

In [116]:
mylist.append(60)
mylist

[10, 20, 30, 40, 50, 60]

In [117]:
x

[10, 20, 30, 40, 50, 60]

In [118]:
b

array([84, 66, 86, 46, 60,  4, 96, 86, 58, 20, 60, 46])

In [120]:
b[b<20]  # get even numbers (i.e., b) < 20

array([4])

In [121]:
b

array([84, 66, 86, 46, 60,  4, 96, 86, 58, 20, 60, 46])

In [124]:
# we now want all even numbers between 30 and 70
c = b[b > 30]
c

array([84, 66, 86, 46, 60, 96, 86, 58, 60, 46])

In [125]:
# Now that we have even numbers > 30, we'll find elements of c < 70
c[c<70]

array([66, 46, 60, 58, 60, 46])

In [126]:
a

array([67,  5, 84, 66, 86, 46, 11, 11, 60, 59,  4, 93, 41, 79, 96, 11, 86,
       75, 58, 20, 43, 60, 93, 46, 83])

In [129]:
a[a%2]  # a common mistake -- we got an array of ints, and so it did fancy indexing!

array([ 5,  5, 67, 67, 67, 67,  5,  5, 67,  5, 67,  5,  5,  5, 67,  5, 67,
        5, 67, 67,  5, 67,  5, 67,  5])

In [130]:
a[0]

67

In [131]:
a[1]

5

In [132]:
a[a%2==1]

array([67,  5, 11, 11, 59, 93, 41, 79, 11, 75, 43, 93, 83])

In [133]:
a

array([67,  5, 84, 66, 86, 46, 11, 11, 60, 59,  4, 93, 41, 79, 96, 11, 86,
       75, 58, 20, 43, 60, 93, 46, 83])

In [134]:
# NumPy arrays are mutable -- we can change them

a[10] = 9999
a

array([  67,    5,   84,   66,   86,   46,   11,   11,   60,   59, 9999,
         93,   41,   79,   96,   11,   86,   75,   58,   20,   43,   60,
         93,   46,   83])

In [135]:
# use fancy indexing for assignment, not just retrieval
a[[3,5,10]] = 8888
a

array([  67,    5,   84, 8888,   86, 8888,   11,   11,   60,   59, 8888,
         93,   41,   79,   96,   11,   86,   75,   58,   20,   43,   60,
         93,   46,   83])

In [136]:
# use a boolean index for assignment, not just retrieval
a[a%2==0] = 7777
a

array([  67,    5, 7777, 7777, 7777, 7777,   11,   11, 7777,   59, 7777,
         93,   41,   79, 7777,   11, 7777,   75, 7777, 7777,   43, 7777,
         93, 7777,   83])

In [137]:
a

array([  67,    5, 7777, 7777, 7777, 7777,   11,   11, 7777,   59, 7777,
         93,   41,   79, 7777,   11, 7777,   75, 7777, 7777,   43, 7777,
         93, 7777,   83])

In [138]:
a = np.random.randint(0, 100, 25)
a

array([44,  0,  5, 74, 10, 41, 36, 99, 67, 85, 95, 61,  3, 32, 54, 49, 66,
       24,  7, 38, 77, 13, 81, 43, 15])

In [140]:
numbers_to_watch = np.array([41, 85, 32, 49, 66])

a in numbers_to_watch

<ipython-input-140-e29a57db167e>:3: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  a in numbers_to_watch


False

In [141]:
# I want to find all integers that are even and ALSO > 50
a = np.random.randint(0, 100, 25)

a[a%2==0 and a>50]

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [142]:
x = 'test'

if x == 'test':
    print(f'It is True!')
else:
    print(f'It is False!')

It is True!


In [143]:
x = 'test'

if x:  
    print(f'It is True!')
else:
    print(f'It is False!')

It is True!


In [144]:
x == True

False

In [145]:
# In a boolean context (an if statement or while loop), everything in Python
# is considered True, except...

# - 0
# - False
# - None
# - Anything empty

In [146]:
while True:
    name = input("Enter your name: ").strip()
    
    if not name:  # meaning: If we got an empty string, break from the loop
        break
        
    print(f'Hello, {name}!')

Enter your name: asdfafd
Hello, asdfafd!
Enter your name: REuven
Hello, REuven!
Enter your name: adsfaffas
Hello, adsfaffas!
Enter your name: 


In [148]:
# I want to find all integers that are even and ALSO > 50
a = np.random.randint(0, 100, 25)

# We will use the bitwise and (&) operator with NumPy arrays:

a[(a%2==0) & (a>50)]

array([96, 84, 96, 68, 58])

In [149]:
# We can also use the bitwise or operator (|) for "OR" operations on our arrays

In [150]:
a%2==0

array([ True,  True, False, False,  True,  True, False, False,  True,
       False, False,  True, False, False,  True,  True, False,  True,
        True,  True,  True, False, False,  True,  True])

In [151]:
a>50

array([False, False, False,  True, False, False,  True,  True,  True,
        True,  True, False,  True, False, False,  True, False,  True,
        True,  True, False, False,  True, False, False])

# Exercises: NumPy and boolean indexes

1. Create a NumPy array with 25 random integers between 0 and 100.
2. Find the even numbers less than 20, in one statement.
3. Find the even numbers between 30 and 70 in one statement.
4. Replace the 2nd, 4th, and 6th even numbers with 60

In [152]:
a

array([36,  6, 15, 95,  8, 28, 97, 93, 96, 65, 51, 26, 67, 49, 42, 84, 21,
       96, 68, 58,  4, 41, 55,  2, 30])

In [153]:
a*5

array([180,  30,  75, 475,  40, 140, 485, 465, 480, 325, 255, 130, 335,
       245, 210, 420, 105, 480, 340, 290,  20, 205, 275,  10, 150])

In [154]:
a<5

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False,  True, False, False,  True, False])

In [156]:
a[a<5]  # return elements < 5

array([4, 2])

In [161]:
np.random.seed(0)
a = np.random.randint(0, 100, 25)
a

array([44, 47, 64, 67, 67,  9, 83, 21, 36, 87, 70, 88, 88, 12, 58, 65, 39,
       87, 46, 88, 81, 37, 25, 77, 72])

In [164]:
a[(a%2==0) & (a<20)]

array([12])

In [165]:
a[(a%2==0) & (a>30) & (a<70)]

array([44, 64, 36, 58, 46])

In [170]:
b = a[a%2==0]
b[[2,4,6]] = 60
b

array([44, 64, 60, 70, 60, 88, 60, 58, 46, 88, 72])

In [171]:
# show odd numbers > mean

a[(a%2==1) & (a>a.mean())]

array([67, 67, 83, 87, 65, 87, 81, 77])

In [175]:
# outliers -- smaller than mean-std, or bigger than mean+std
a[(a<a.mean()-a.std()) | (a>a.mean()+a.std())]

array([ 9, 83, 21, 87, 88, 88, 12, 87, 88, 25])

In [176]:
# outliers -- smaller than mean-std, or bigger than mean+std
a[(a<a.mean()-2*a.std()) | (a>a.mean()+2*a.std())]

array([], dtype=int64)

In [177]:
a = np.array([10, 20, 30, 40, 50])
a

array([10, 20, 30, 40, 50])

In [178]:
a.dtype

dtype('int64')

In [179]:
# %pylab inline

np.int64
np.dtype('int64')

dtype('int64')

In [180]:
int64  # thanks to %pylab inline's import
dtype('int64')  # again, thanks to %pylab inline's import

dtype('int64')

In [181]:
a = np.array([10, 20, 30, 40, 50], dtype=np.int8)
a

array([10, 20, 30, 40, 50], dtype=int8)

In [182]:
a**2

array([ 100, -112, -124,   64,  -60], dtype=int8)

In [183]:
a = np.array([10, 20, 30, 40, 50], dtype=np.uint8)
a

array([10, 20, 30, 40, 50], dtype=uint8)

In [184]:
a**2

array([100, 144, 132,  64, 196], dtype=uint8)

In [185]:
a

array([10, 20, 30, 40, 50], dtype=uint8)

In [186]:
a[2] = 66
a

array([10, 20, 66, 40, 50], dtype=uint8)

In [187]:
a[2] = '77'

In [188]:
a

array([10, 20, 77, 40, 50], dtype=uint8)

In [189]:
a[2] = 123.456
a

array([ 10,  20, 123,  40,  50], dtype=uint8)

In [190]:
a[2] = 'abcd'

ValueError: invalid literal for int() with base 10: 'abcd'

In [191]:
a = np.array([10, 20, 30.5, 40, 50])
a

array([10. , 20. , 30.5, 40. , 50. ])

In [192]:
a.dtype

dtype('float64')

In [193]:
a[2] = 100
a

array([ 10.,  20., 100.,  40.,  50.])

In [194]:
float(100)

100.0

In [196]:
a = np.array([10, 20, 30, 40, 50])
a.dtype

dtype('int64')

In [197]:
a.dtype = np.int32   # NEVER DO THIS!!!!!
a

array([10,  0, 20,  0, 30,  0, 40,  0, 50,  0], dtype=int32)

In [198]:
a.dtype = np.int8
a

array([10,  0,  0,  0,  0,  0,  0,  0, 20,  0,  0,  0,  0,  0,  0,  0, 30,
        0,  0,  0,  0,  0,  0,  0, 40,  0,  0,  0,  0,  0,  0,  0, 50,  0,
        0,  0,  0,  0,  0,  0], dtype=int8)

In [199]:
a.dtype = np.float64
a

array([4.94e-323, 9.88e-323, 1.48e-322, 1.98e-322, 2.47e-322])

In [200]:
a.dtype = np.int64
a

array([10, 20, 30, 40, 50])

In [201]:
# to change an array's dtype, use the "astype" method
# this returns a new array with the same values, but a new type

a.astype(np.float64)

array([10., 20., 30., 40., 50.])

In [202]:
a.astype(np.int16)

array([10, 20, 30, 40, 50], dtype=int16)

In [203]:
a = a.astype(np.int16)
a

array([10, 20, 30, 40, 50], dtype=int16)

In [204]:
a = np.random.rand(10)
a

array([0.0871293 , 0.0202184 , 0.83261985, 0.77815675, 0.87001215,
       0.97861834, 0.79915856, 0.46147936, 0.78052918, 0.11827443])

In [205]:
a = a * 100  # now I'll have 10 random floats between 0-100
a

array([ 8.71292997,  2.02183974, 83.26198455, 77.81567509, 87.00121482,
       97.86183422, 79.91585642, 46.14793623, 78.05291763, 11.82744259])

In [206]:
a.astype(np.int64)

array([ 8,  2, 83, 77, 87, 97, 79, 46, 78, 11])

In [207]:
a = np.array('this is a very strange test'.split())
a

array(['this', 'is', 'a', 'very', 'strange', 'test'], dtype='<U7')

In [208]:
a[0] = 'abcdefg'
a

array(['abcdefg', 'is', 'a', 'very', 'strange', 'test'], dtype='<U7')

In [209]:
a[1] = 'hijklmnopqrst'
a

array(['abcdefg', 'hijklmn', 'a', 'very', 'strange', 'test'], dtype='<U7')

In [210]:
a = np.array('10 20 30 40 50'.split())
a

array(['10', '20', '30', '40', '50'], dtype='<U2')

In [211]:
a.astype(np.int64)

array([10, 20, 30, 40, 50])

# Exercises: dtypes 

1. Generate a NumPy array with 20 elements, all random floats from 0-100.
2. Find the numbers whose integer portion is even.  (Meaning, 25.3 would be odd, but 26.3 would be even.)
3. Find the maximum such "even" number.
4. Create a NumPy array based on a string with spaces between the integers.
5. What are the mean and standard deviation of these numbers?


In [213]:
np.random.seed(0)
a = np.random.rand(20)
a

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ,
       0.64589411, 0.43758721, 0.891773  , 0.96366276, 0.38344152,
       0.79172504, 0.52889492, 0.56804456, 0.92559664, 0.07103606,
       0.0871293 , 0.0202184 , 0.83261985, 0.77815675, 0.87001215])

In [214]:
a = a*100
a

array([54.88135039, 71.51893664, 60.27633761, 54.4883183 , 42.36547993,
       64.58941131, 43.75872113, 89.17730008, 96.36627605, 38.34415188,
       79.17250381, 52.88949198, 56.80445611, 92.55966383,  7.10360582,
        8.71292997,  2.02183974, 83.26198455, 77.81567509, 87.00121482])

In [217]:
a[a.astype(np.int64) % 2 == 0]

array([54.88135039, 60.27633761, 54.4883183 , 42.36547993, 64.58941131,
       96.36627605, 38.34415188, 52.88949198, 56.80445611, 92.55966383,
        8.71292997,  2.02183974])

In [218]:
a[a.astype(np.int64) % 2 == 0].max()

96.36627605010293

In [219]:
a = np.array('10 20 30 50 70 2 15'.split())
a

array(['10', '20', '30', '50', '70', '2', '15'], dtype='<U2')

In [221]:
a.astype(np.int64).sum()

197

In [222]:
a.astype(np.int64).mean()

28.142857142857142

In [223]:
a.astype(np.int64).std()

22.31225525790429

In [224]:
a.astype('uint8')


array([10, 20, 30, 50, 70,  2, 15], dtype=uint8)

In [228]:
a

array(['10', '20', '30', '50', '70', '2', '15'], dtype='<U2')

In [229]:
a

array(['10', '20', '30', '50', '70', '2', '15'], dtype='<U2')

In [230]:
np.random.seed(0)
a = np.random.rand(20) * 100
a

array([54.88135039, 71.51893664, 60.27633761, 54.4883183 , 42.36547993,
       64.58941131, 43.75872113, 89.17730008, 96.36627605, 38.34415188,
       79.17250381, 52.88949198, 56.80445611, 92.55966383,  7.10360582,
        8.71292997,  2.02183974, 83.26198455, 77.81567509, 87.00121482])

In [231]:
a.astype('uint8')


array([54, 71, 60, 54, 42, 64, 43, 89, 96, 38, 79, 52, 56, 92,  7,  8,  2,
       83, 77, 87], dtype=uint8)

In [232]:
a.astype('uint8')[a%2==0]
x

array([], dtype=uint8)

In [234]:
a%2 == 0

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False])

In [235]:
a.astype('uint8')[a.astype('uint8')%2==0]


array([54, 60, 54, 42, 64, 96, 38, 52, 56, 92,  8,  2], dtype=uint8)

In [236]:
a = np.random.randint(0, 100, 20)
a

array([82, 99, 88, 49, 29, 19, 19, 14, 39, 32, 65,  9, 57, 32, 31, 74, 23,
       35, 75, 55])

In [237]:
a

array([82, 99, 88, 49, 29, 19, 19, 14, 39, 32, 65,  9, 57, 32, 31, 74, 23,
       35, 75, 55])

In [238]:
a.dtype

dtype('int64')

In [239]:
b = a.astype(np.int32)  

In [240]:
a == b

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [241]:
id(a)

4957708736

In [242]:
id(b)

4957708976

In [243]:
a.astype(np.int32)

array([82, 99, 88, 49, 29, 19, 19, 14, 39, 32, 65,  9, 57, 32, 31, 74, 23,
       35, 75, 55], dtype=int32)

In [244]:
scores = np.array([95, 90, 100, 92, 98])
scores.mean()

95.0

In [245]:
scores = np.array([95, 90, 100, 0, 98])
scores.mean()

76.6

In [246]:
scores = np.array([95, 90, 100, nan, 98])  # nan == not a number


In [247]:
type(nan)

float

In [248]:
nan == nan

False

In [249]:
nan + 3

nan

In [250]:
nan * 2

nan

In [251]:
scores

array([ 95.,  90., 100.,  nan,  98.])

In [252]:
scores.mean()

nan

In [253]:
scores[scores != nan].mean()

nan

In [254]:
scores[scores != nan]

array([ 95.,  90., 100.,  nan,  98.])

In [255]:
isnan(scores)

array([False, False, False,  True, False])

In [256]:
scores[isnan(scores)]

array([nan])

In [257]:
# in NumPy, we can use
# - & for "and"
# - | for "or"
# - ~ (tilde) for "not"

In [258]:
~isnan(scores)

array([ True,  True,  True, False,  True])

In [260]:
scores[~isnan(scores)].mean()

95.75

In [261]:
# how can we deal with nan?
# - ignore it (not recommended)
# - remove it
# - interpolation (meaning: replace nan with some other value)

nan

In [262]:
a

array([82, 99, 88, 49, 29, 19, 19, 14, 39, 32, 65,  9, 57, 32, 31, 74, 23,
       35, 75, 55])

In [263]:
a.mean()

46.3

In [266]:
scores

array([ 95.,  90., 100.,  nan,  98.])

In [267]:
# replace any nan values
# with the mean of the non-nan values

scores[isnan(scores)] = scores[~isnan(scores)].mean()

In [268]:
scores

array([ 95.  ,  90.  , 100.  ,  95.75,  98.  ])

In [269]:
scores.mean()

95.75

In [270]:
a = np.array([10, 20, 30, 40, 50])
a

array([10, 20, 30, 40, 50])

In [271]:
a[2] = nan

ValueError: cannot convert float NaN to integer

In [272]:
a = a.astype(np.float64)
a

array([10., 20., 30., 40., 50.])

In [273]:
a[2] = nan
a

array([10., 20., nan, 40., 50.])

In [274]:
a = array([ 95.,  90., 100.,  nan,  98.])
a.dtype

dtype('float64')

# Exercises: Using and working with nan

1. Create an array of 50 floats, all between 0 and 1000.
2. Find the numbers that are < mean-std or > mean+std.
3. Replace all of these numbers with nan.
4. Replace all of the nan values with the mean of the non-nan values.

In [275]:
np.median(a)

nan

In [277]:
from scipy import stats
stats.mode(a)

ModeResult(mode=array([90.]), count=array([1]))

In [278]:
a = np.array([10, 20, 30, 20, 30, 40, 30, 40, 40, 40, 50])
stats.mode(a)

ModeResult(mode=array([40]), count=array([4]))

In [279]:
a = np.random.rand(50) * 1000
a

array([216.55035442, 135.21817341, 324.14100779, 149.67486718,
       222.32138825, 386.48898113, 902.59847553, 449.94998991,
       613.06345788, 902.34858317,  99.28035036, 969.80906775,
       653.1400358 , 170.90958514, 358.15216697, 750.68614122,
       607.83066872, 325.04722901,  38.42542647, 634.27405796,
       958.94926862, 652.79031701, 635.0588736 , 995.29956768,
       581.85032944, 414.36858823, 474.69750229, 623.51010113,
       338.00761484, 674.75232226, 317.20174207, 778.34548203,
       949.57105345, 662.52686695,  13.57163561, 622.84609555,
       673.65963084, 971.9450025 , 878.19347135, 509.62437672,
        55.7146937 , 451.15921452,  19.98766541, 441.71092125,
       979.58672881, 359.44446397, 480.89353084, 688.66118281,
       880.47588925, 918.23546636])

In [284]:
a[(a<a.mean()-a.std())  | (a>a.mean()+a.std())]

array([216.55035442, 135.21817341, 149.67486718, 222.32138825,
       902.59847553, 902.34858317,  99.28035036, 969.80906775,
       170.90958514,  38.42542647, 958.94926862, 995.29956768,
       949.57105345,  13.57163561, 971.9450025 , 878.19347135,
        55.7146937 ,  19.98766541, 979.58672881, 880.47588925,
       918.23546636])

In [285]:
a[(a<a.mean()-a.std())  | (a>a.mean()+a.std())] = nan
a

array([         nan,          nan, 324.14100779,          nan,
                nan, 386.48898113,          nan, 449.94998991,
       613.06345788,          nan,          nan,          nan,
       653.1400358 ,          nan, 358.15216697, 750.68614122,
       607.83066872, 325.04722901,          nan, 634.27405796,
                nan, 652.79031701, 635.0588736 ,          nan,
       581.85032944, 414.36858823, 474.69750229, 623.51010113,
       338.00761484, 674.75232226, 317.20174207, 778.34548203,
                nan, 662.52686695,          nan, 622.84609555,
       673.65963084,          nan,          nan, 509.62437672,
                nan, 451.15921452,          nan, 441.71092125,
                nan, 359.44446397, 480.89353084, 688.66118281,
                nan,          nan])

In [289]:
# replace all of the nan values with the mean of the non-nan values
a[np.isnan(a)] = a[~np.isnan(a)].mean()

In [290]:
a

array([533.9269963 , 533.9269963 , 324.14100779, 533.9269963 ,
       533.9269963 , 386.48898113, 533.9269963 , 449.94998991,
       613.06345788, 533.9269963 , 533.9269963 , 533.9269963 ,
       653.1400358 , 533.9269963 , 358.15216697, 750.68614122,
       607.83066872, 325.04722901, 533.9269963 , 634.27405796,
       533.9269963 , 652.79031701, 635.0588736 , 533.9269963 ,
       581.85032944, 414.36858823, 474.69750229, 623.51010113,
       338.00761484, 674.75232226, 317.20174207, 778.34548203,
       533.9269963 , 662.52686695, 533.9269963 , 622.84609555,
       673.65963084, 533.9269963 , 533.9269963 , 509.62437672,
       533.9269963 , 451.15921452, 533.9269963 , 441.71092125,
       533.9269963 , 359.44446397, 480.89353084, 688.66118281,
       533.9269963 , 533.9269963 ])

In [291]:
a.mean()

533.9269963000793

In [292]:
np.random.seed(0)
a = np.random.rand(50) * 1000
a

array([548.81350393, 715.18936637, 602.76337607, 544.883183  ,
       423.65479934, 645.89411307, 437.58721126, 891.77300078,
       963.6627605 , 383.44151883, 791.72503808, 528.89491975,
       568.04456109, 925.59663829,  71.0360582 ,  87.1292997 ,
        20.21839744, 832.61984555, 778.15675095, 870.01214825,
       978.61834223, 799.15856422, 461.47936225, 780.52917629,
       118.27442587, 639.92102133, 143.35328741, 944.66891705,
       521.84832175, 414.66193999, 264.5556121 , 774.23368943,
       456.15033222, 568.43394887,  18.78980044, 617.63549708,
       612.09572272, 616.93399687, 943.74807851, 681.8202991 ,
       359.50790057, 437.0319538 , 697.63119593,  60.22547163,
       666.76671545, 670.63786962, 210.38256107, 128.92629765,
       315.42835092, 363.71077094])

In [293]:
a.mean()

537.965118275541

In [294]:
a.std()

272.26582292177585

In [295]:
a[(a<a.mean()-a.std())  | (a>a.mean()+a.std())] = nan


In [296]:
a[~np.isnan(a)].mean()

575.7707803466524

In [297]:
a[~np.isnan(a)].std()

138.56077167058928

In [298]:
a[np.isnan(a)] = a[~np.isnan(a)].mean()

In [299]:
a.mean()

575.7707803466524

In [300]:
a.std()

110.84861733647142

In [301]:
stats.mode(a)

ModeResult(mode=array([575.77078035]), count=array([18]))

In [302]:
type(a)

numpy.ndarray

In [303]:
a = np.random.randint(0, 100, 24)
a

array([42, 84, 75, 68,  6, 68, 47,  3, 76, 52, 78, 15, 20, 99, 58, 23, 79,
       13, 85, 48, 49, 69, 41, 35])

In [304]:
a.shape

(24,)

In [305]:
a.reshape(8, 3)

array([[42, 84, 75],
       [68,  6, 68],
       [47,  3, 76],
       [52, 78, 15],
       [20, 99, 58],
       [23, 79, 13],
       [85, 48, 49],
       [69, 41, 35]])

In [306]:
a.reshape(6, 4)

array([[42, 84, 75, 68],
       [ 6, 68, 47,  3],
       [76, 52, 78, 15],
       [20, 99, 58, 23],
       [79, 13, 85, 48],
       [49, 69, 41, 35]])

In [307]:
a.reshape(8, 9)

ValueError: cannot reshape array of size 24 into shape (8,9)

In [308]:
# reshape method returns a new array, with the new shape

In [ ]:
# y